DROP TABLE IF EXISTS codes;

CREATE TABLE codes(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(100) NOT NULL,
  item_id INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS deals;

CREATE TABLE deals(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  item VARCHAR(100) NOT NULL,
  price FLOAT NOT NULL,
  location VARCHAR(200) NOT NULL,
  website VARCHAR(200)
);
